name: flutter_boxicons
description: Boxicons (https://boxicons.com) customization for Flutter. You can use 2K+ more Boxicons.
version: 3.1.0
homepage: https://shasmatic.site
repository: https://github.com/arifai/flutter_boxicons
issue_tracker: https://github.com/arifai/flutter_boxicons/issues
topics:
  - assets
  - icons
  - box-icons

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: Boxicons
      fonts:
        - asset: fonts/Boxicons.ttf
